### ISSUE TITLE
[Bug] Scanner (used in cli, web-api scans) does not seem to scan child iframes

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-service#1003]
## Describe the bug

In both CLI versions 0.2.5 and 0.3.0, the following set of steps results in 0 failures:
- create empty directory
- npm i accessibility-insights-scan@0.x.y
- npx ai-scan --url https://karanbirsingh.github.io/iframes

This page has iframes with issues, but the iframe results do not show up. This would be reflected in the service, CLI, and accessibility-insights-action.

The target page has a [demo site](https://markreay.github.io/AU/before.html) inside an iframe. When this site is scanned in the web extension, if we have iframe permissions, we see the errors from the child frame.

By default, I wasn't able to see iframe results when using axe-puppeteer alone either:
- clone this [repository](https://github.com/karanbirsingh/axe-puppeteer-iframes)
- yarn install
- node .\test.js
- wait for script to finish (intentional timeout to help rule out loading delay)
- notice some issues, but none from the child frame

It's not clear to me whether the issue is upstream or if we need to add wrapping to ensure we can get results from iframes.

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

**Comment by waabid** [comment]
After #1057 has been merged, I'm not longer able to repro this issue. 🥳

**Comment by lamaks** [comment]
Migrated to new axe puppeteer package to fix the issue
