### ISSUE TITLE
[Bug] Some links times out while navigating because networkidle0 never happens 

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [microsoft/accessibility-insights-service#1139]
## Describe the bug
If you try to scan something like https://dotnet.microsoft.com/learn/dotnet/in-browser-tutorial/2 or https://dotnet.microsoft.com/languages from the cloud service, it will time out every time because we wait for networkidle0  and this event never fires for those links

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

**Comment by adarshrema** [comment]
On initial investigation, seems to be an issue related to axe-core running in a container because the scanning is successful with Accessibility Insights for Web. Requires more investigation.

**Comment by ferBonnin** [comment]
Per conversation with Maxim, this will be addressed as part of feature work. @lamaks please add link in feature

**Comment by lamaks** [comment]
Fixed node memory allocation to resolve axe core hang
