### ISSUE TITLE
[Bug] URLs that would redirect but have the same domain are not scanned when crawling

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-service#1154]
## Describe the bug

Context: The browser (Edge Version 87.0.664.52 (Official build) (64-bit)) redirects `https://www.github.com/` to `https://github.com/`. 

Problem: When running ai-scan cli with `--url https://www.github.com/`, the base page `https://github.com/` is scanned, but all the links on this page have an actual base URL of `https://github.com/` and are not considered as discovered links, because they don't match the parameter `https://www.github.com/`.

Since the browser redirects `https://www.github.com/` to `https://github.com/` (same domain), I would think that links/pages with and without the www would be treated the same. Additionally, the console output even indicates that it is processing `https://github.com/` instead of the originally-entered `https://www.github.com/`, so it looks like it was scanning from the redirected URL.

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

## To Reproduce

1. Open Terminal/Command Prompt
2. Run `ai-scan --crawl true --url https://www.github.com/`
3. See the following in the console output:
```
Processing page https://github.com/                                                                                  
Discovered 0 links on page https://github.com/
```
4. Repeat step 2 but with `--url https://github.com/` and see a non-zero number of discovered links in the console output

## Expected behavior

Discover and scan the same links when running:
- `ai-scan --crawl true --url https://www.github.com/` and
- `ai-scan --crawl true --url https://github.com/`

**Comment by adarshrema** [comment]
Fix to ensure expected behavior to crawl and scan child URLs within the redirected base URL.

**Comment by AhmedAbdoOrtiga** [comment]
As we agreed, the user should know that the website includes the subdomain or not, for example in GitHub case, the user should enter https://github.com, if he enters https://www.github.com, we won't do anything about it
