### ISSUE TITLE
[Bug] Scan job manager creates duplicate scan tasks

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#1222]
<img width="834" alt="Screen Shot 2021-01-12 at 6 31 07 PM" src="https://user-images.githubusercontent.com/40576301/104398879-74a2f980-5504-11eb-9c85-33722b055b1f.png">

<img width="753" alt="Screen Shot 2021-01-12 at 6 27 43 PM" src="https://user-images.githubusercontent.com/40576301/104398887-7967ad80-5504-11eb-8317-4d2c39cb72ce.png">

<img width="753" alt="Screen Shot 2021-01-12 at 6 27 59 PM" src="https://user-images.githubusercontent.com/40576301/104398893-7d93cb00-5504-11eb-81f5-f13e89845609.png">

**Comment by ferBonnin** [comment]
moving to Active since @lamaks is working on this
