### ISSUE TITLE
[Bug] Noisy "ScanTaskFailed" events on combined results generation retry

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-service#1282]
## Describe the bug

We've been getting a lot of ScanTaskFailed events from scans that actually succeeded, but the first attempt failed because of write collisions when the combined results are updated. This results in a lot of false failures in the dashboard. Since we expect occasional update failures for the combined results, and handle that case, these shouldn't be logged as failed scans.

Potential solutions (not mutually exclusive):
- Increase the number of retries to generate combined results (We currently try twice)
- Use separate telemetry events to track scan failures vs combined scan/deepScan failures (and differentiate these in the dashboard)

## Area

- [ ] Install script
- [ ] Update script
- [X] Service

## Expected behavior

We should not see failure spikes from expected behavior for combined scans.

## Log files

From the first failed scan attempt, after two attempts to update combined results:
<img width="339" alt="logs with two attempts to retrieve axe scan results, and then a failure message" src="https://user-images.githubusercontent.com/55459788/107107936-35a55280-67e9-11eb-8104-54e660aeb165.PNG">

From the second successful scan attempt (for the same scan id):
<img width="338" alt="logs showing that the website scan results were successfully updated, and the scan succeeded" src="https://user-images.githubusercontent.com/55459788/107107947-3fc75100-67e9-11eb-9d3f-f7bc605a947a.PNG">

## Screenshots

<img width="595" alt="failed scans graph, showing 407 failed scans over 4 hours" src="https://user-images.githubusercontent.com/55459788/107107911-08f13b00-67e9-11eb-97ba-6a88beb95309.PNG">

**Comment by ferBonnin** [comment]
per conversation with @lamaks let's address this and ensure we are not sending this event on retry.

**Comment by pownkel** [comment]
Closing, as this seems to have been solved by #1319
