### ISSUE TITLE
[Bug] Investigate why some scans are not found 

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [microsoft/accessibility-insights-service#1295]
## Describe the bug

Some URLS gets deleted from either the batch scan container or the queue container before it make it to the permanent container.
That could be one of the following reasons:
  - The batch scan feed function failed for some reason (either cosmos trigger failed or internal error).
  - The url expired and deleted (7 days limit) in the queue container before it's picked up by the scan-request-sender.
  - Or it could be something else.

We need to come up with a design that retry to run batch-scan-feed function if it fails .

**Also we need to improve our telemetries as a part of solving this too:**
  - if the above scenario happens, we don't have enough telemetry to track what happened!

**This could end up a feature request**

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

**Comment by ferBonnin** [comment]
Per conversation with the team. to tackle with feature work. @ferBonnin to link to feature
