### ISSUE TITLE
[Bug] Handle meta refresh client-side redirects more robustly

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-service#1346]
## Describe the bug

When running the CLI against a webpage that utilizes `<meta http-equiv="refresh" content="0;URL='http://microsoft.com/'" />` to initiate a [client-side redirect](https://www.w3.org/TR/WCAG20-TECHS/H76.html), the results can be inconsistent. Depending on how fast the redirect occurs, the following states are possible:
1. scanning occurs on pre-redirect page
2. scanning occurs on post-redirect page
3. scanning fails because redirection interrupts scan

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

## To Reproduce

Run the CLI against this HTML page:

```html
<html xmlns="http://www.w3.org/1999/xhtml">    
  <head>      
    <title>Test</title>      
    <meta http-equiv="refresh" content="0;URL='http://microsoft.com/'" />    
  </head>    
  <body> 
    <p>This page has moved.</p> 
  </body>  
</html>     
```

Or against these URLs:
- https://adoption.microsoft.com/virtual-hub/humans-of-it/humans-of-it-community-mentors-and-student-ambassador-voices/
- https://adoption.microsoft.com/virtual-hub/humans-of-it/community-mentors-app-walkthrough-demo/
- https://adoption.microsoft.com/virtual-hub/humans-of-it/productivity-for-humans-series-meet-jeff-stokes/

## Expected behavior

We shouldn't have option 3, but options 1 or 2 seem okay if we pick one to be consistent. Maybe something like this is worth trying: https://github.com/puppeteer/puppeteer/issues/3036

**Comment by lamaks** [comment]
@karanbirsingh To repro the issue we need the actual URL resulted this behavior. Please add the URL to the bug description.

**Comment by karanbirsingh** [comment]
Here are some production URLs:
- https://adoption.microsoft.com/virtual-hub/humans-of-it/humans-of-it-community-mentors-and-student-ambassador-voices/
- https://adoption.microsoft.com/virtual-hub/humans-of-it/community-mentors-app-walkthrough-demo/
- https://adoption.microsoft.com/virtual-hub/humans-of-it/productivity-for-humans-series-meet-jeff-stokes/

or test code in original issue

**Comment by ferBonnin** [comment]
reviewed with Maxim

**Comment by lamaks** [comment]
Resolved by supporting script redirection detection
