### ISSUE TITLE
[Bug] Use MSI to connect to Cosmos DB

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#1370]
Using connection string auth to Cosmos DB. Move to MSI or AAD for auth to Cosmos DB.
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

Ref bug 8183

**Comment by ferBonnin** [comment]
Reviewed with Maxim, marking as ready for work

**Comment by pownkel** [comment]
Currently blocked by [this issue](https://github.com/Azure/azure-sdk-for-js/issues/17041)
