### ISSUE TITLE
[Bug] Investigate migrating to RBAC Key Vault

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#1371]
Investigate migrating to RBAC Key Vault
https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli
https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-migration

Ref bug 8182

**Comment by ferBonnin** [comment]
Reviewed with Maxim, marking as ready for work
