### ISSUE TITLE
[Bug] Mark "duplicate-id" rule as a best practice rule

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-service#1374]
## Describe the bug

Based on feedback from users we tested to check the user impact of duplicate ID failures on static elements. We found no user impact on the experience with any of the ATs including Narrator, JAWS, NVDA, Dragon, Windows Speech Recognition.

After further discussions with the Tooling Advisory Board, we decided to make this a best practice rule
## Area

- [ ] Install script
- [ ] Update script
- [x] Service

## Expected behavior

duplicate-id failures are no longer highlighted. 
(please note both duplicate-id-aria and duplicate-id-active should still be highlighted)

## Additional context

same bug in Web repo: [#4112](https://github.com/microsoft/accessibility-insights-web/issues/4102)

**Comment by tohmjudson-ms** [comment]
I think I am ready to dive into this one next @ferBonnin :)

**Comment by ferBonnin** [comment]
thanks @tohmjudson-ms! I think @dbjorge tackled this one with PR #1393; @dbjorge can you please confirm?

**Comment by dbjorge** [comment]
Yep, this should be all set! We expect to release both web and service over the next few business days with these changes.

**Comment by tohmjudson-ms** [comment]
Excellent!

**Comment by dbjorge** [comment]
Resolved in #1393
