### ISSUE TITLE
Getting error logs. Unable to get the index.html file 

### ISSUE THREAD

**Issue by Sayali1638** [microsoft/accessibility-insights-service#1910]
I have container inside which my jenkins is running.
Pipeline for accessibility insights have been created.
Downloaded following packages:
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

In pipeline I have done npm install for following:
@lhci/cli
puppeteer

and performed following:
ai-scan --crawl --restart --url https://partsunlimited-web-apps.azurewebsites.net/

Getting following error:

ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://partsunlimited-web-apps.azurewebsites.net/","retryCount":1,"id":"yj78jGCMV1f4reu"}
  Error: browser.newPage() timed out.
      at Timeout._onTimeout (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/extensure-nodejs/lib/node_modules/accessibility-insights-scan/node_modules/apify/build/utils.js:360:49)
      at listOnTimeout (node:internal/timers:568:17)
      at processTimers (node:internal/timers:510:7)
INFO  Launching Puppeteer {"args":["--disable-dev-shm-usage","--no-sandbox","--disable-setuid-sandbox","--js-flags=--max-old-space-size=8192","--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"],"defaultViewport":{"width":1920,"height":1080,"deviceScaleFactor":1},"timeout":15000,"headless":true}
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://partsunlimited-web-apps.azurewebsites.net/","retryCount":2,"id":"yj78jGCMV1f4reu"}
  Error: browser.newPage() timed out.
      at Timeout._onTimeout (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/extensure-nodejs/lib/node_modules/accessibility-insights-scan/node_modules/apify/build/utils.js:360:49)
      at listOnTimeout (node:internal/timers:568:17)
      at processTimers (node:internal/timers:510:7)

Something went wrong. Please try again later. If this persists, search for a known issue or file a new one at https://github.com/microsoft/accessibility-insights-service/issues.
Error log was saved as /var/jenkins_home/workspace/accessibility-insights-scan-pipeline/ai_scan_cli_output/ai-cli-errors-20220118-052510.log

THe content of log files are as follows:

{
  name: 'NotFoundError',
  message: 'Key not found in database [[object Object]]',
  stack: 'NotFoundError: Key not found in database [[object Object]]\n' +
    '    at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallat
    '    at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallat
}

Please let me know why this is occuring.

**Comment by vishalgoyal16444** [comment]
@karanbirsingh: Thank you. Please update once your weekly review is completed.

**Comment by lamaks** [comment]
@vishalgoyal16444 The web page your are trying to scan is not available.  The log indicates browser timeout `Error: browser.newPage() timed out.` If web browser can open web page the tool will scan it successfully as well.

**Comment by Sayali1638** [comment]
@lamaks  : We have deployed our accessibility-insights pipeline on 2 VM. It is working good for 1 VM and failing with above error with other.
Could you please explain, if we are missing on anything?

**Comment by lamaks** [comment]
@Sayali1638 This is depends on VM/Azure web app network configuration. The VM's local web browser should be able to access a web page that the tool is scanning. You can connect to VM terminal and validate this via local web browser or run the tool in a debug mode with `--debug` option:

ai-scan --crawl --restart --url https://partsunlimited-web-apps.azurewebsites.net/ **--debug**
