### ISSUE TITLE
[Feature Request] Scan tool should support custom headers

### ISSUE THREAD

**Issue by azt3k** [microsoft/accessibility-insights-service#2425]
## Is your feature request related to a problem? Please describe.

I need to be able to run scans on non-production sites - these often have IP whitelists or basic auth. Having the ability to provide custom headers would solve this problem.

## Describe the solution you'd like

Have an option like `--extra-headers '{"Name": "Value"}'`

## Describe alternatives you've considered

There isn't really an alternative 

## Additional context

I am currently using a version of TheA11yMachine which works well, but is very dated. Would be nice to move to something that is actually maintained and supports newer WCAG standards.

**Comment by lamaks** [comment]
Implemented in version 2.1.0 https://www.npmjs.com/package/accessibility-insights-scan
