### ISSUE TITLE
[Bug] scan CLI package reports apify's DEFAULT_USER_AGENT instead of the real user agent in report footers

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-service#2426]
## Describe the bug

Prior to #2419 being merged, Chrome 101.0.4951.54 ([link to log](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=43331&view=logs&j=c5c5d0ad-9fc4-5fcb-d69d-7db2ecc16a23&t=416c895d-020b-5518-b8c1-2de17bd8a38d)) was used. this version of Chrome dates from April 2022. 

After #2419 was merged, we expected a newer version of Chrome to be used. However, [logs with the update](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=44231&view=logs&j=c5c5d0ad-9fc4-5fcb-d69d-7db2ecc16a23&t=416c895d-020b-5518-b8c1-2de17bd8a38d) still show 101.0.4951.54.

This brings up some potential issues:
1. If a Chrome bug gets fixed, it may not get reflected in the scan results.
2. it's not clear what is determining the Chrome version. If it depends on an external factor, results may be inconsistent between different host environments.
3. From a perf perspective, Puppeteer may be downloading a browser version that it never uses.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

## To Reproduce

5. Click on '....'
6. Scroll down to '....'
7. See error

## Expected behavior

We'd expect the browser version to be controlled by the scanner, and ideally to be the most recent version that Puppeteer knows about. Neither of those

**Comment by dbjorge** [comment]
I looked into this a bit and I think the scan library is actually using the expected (puppeteer-bundled) version of Chromium, but there are two issues confusing the situation:

* `/packages/crawler/src/crawler/puppeteer-crawler-engine.ts` used by the scan library doesn't pass any `userAgent` to the Apify Puppeteer `launchContext`. [Apify's default behavior with no explicit user agent specified in our scenario is to fake a hard-coded default user agent](https://github.com/apify/crawlee/blob/v2.3.2/src/browser_launchers/puppeteer_launcher.js#L150-L155), which is where the `101.0.4951.54` comes from. I think this only affects the scan-cli package based path; in the cloud service, the user agent appears to be controlled instead by [/packages/scanner-global-library/src/user-agent-plugin.ts](https://github.com/microsoft/accessibility-insights-service/blob/main/packages/scanner-global-library/src/user-agent-plugin.ts). It would be nice to converge the behavior between the two scenarios - the user impact here is that Accessibility Insights for Azure DevOps' generated reports misreport the user agent in the report footer.
* The action contains [a misleading log line here](https://github.com/microsoft/accessibility-insights-action/blob/ced3b7cb2dacd706d8c7dad96ed806d9963a3b88/packages/shared/src/scanner/scanner.ts#L114) that suggests incorrectly that when no user agent is specified, it falls back to the "system default", when actually the default behavior is to fall back to `Puppeteer.executablePath()`, which is the puppeteer-bundled version.

I'll retitle this bug based on the practical user impact of the first point. The second point is an issue in the action repo, not the service repo.

**Comment by lamaks** [comment]
To report actual browser user agent string some additional work is required for cli package.

**Comment by lamaks** [comment]
Resolved in version 2.1.0 https://www.npmjs.com/package/accessibility-insights-scan
