### ISSUE TITLE
[Bug] Scan CLI package incorrectly treats 304 responses as errors

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-service#2434]
## Describe the bug

We received a support request from a user whose AI4ADO setup involves a flow similar to the one described in #2413, except with the final page load involving a request using an `If-None-Match` header and a `304: Not Modified` response rather than a request-free cache hit.

The user reports that even after verifying they're on AI4ADO v3.4.0 (with the Puppeteer update), they're still seeing errors during scanning based on the scanner reporting a `errorType: 'HttpErrorCode', statusCode: 304`.

We had incorrectly expected this case to be addressed along with the Puppeteer update that fixed #2413 (https://github.com/puppeteer/puppeteer/issues/9965), but it turns out that Puppeteer treats the case with the 304 differently from the case with the client-side cache hit; in the client-side cache hit, it now gives back the `200` response status from the original request, but in the 304 case, it uses the headers and status from the 304 request with the content of the original 200 request.

This behavior (showing status code 304 rather than 200 despite using the body from the original cached request) matches what Chromium's dev tools' Network tab shows. Notably, it does *not* match Playwright's behavior (Playwright uses the status and headers from the original request).

The 304 response is **not an error**; this is the expected and successful behavior of the page in this caching scenario, and Puppeteer reporting the 304 status is expected behavior which matches Chromium's dev tools. The Scan CLI package needs to not treat the 304 status as an error. I'm a bit on the fence about other 3XX status codes - many of them are arguably also non-errors, but in practice now that the #2413 fix is in, it's probably an error condition for us to actually *see* most of them reported by the browser. But 304 specifically is definitely a non-error.

However, in practice, treating it as a non-error is a bit tricker than it sounds; just updating the `response.ok()` test on L14 of `/packages/scanner-global-library/src/page-response-processor.ts` runs into an issue where subsequent parts of response validation try to read headers (particularly, `Content-Type`) which are sent in the cached 200 response, but not present on the 304 response we get from Puppeteer. I've filed https://github.com/puppeteer/puppeteer/issues/10145 with Puppeteer to request clarification about what exactly the expected behavior from Puppeteer is. Based on their response, our options to fix this include:

1. Update service's `response.ok()` check on L14 of `/packages/scanner-global-library/src/page-response-processor.ts` to also accept 304s, and handle header checks that need to use the original 200 response's headers by:
  a. If Puppeteer provides a native option to do this, eg as a fix for https://github.com/puppeteer/puppeteer/issues/10145: Use that
  b. Otherwise, add our own cache tracking behavior to requests to enable our own lookup of headers from the original request (not recommended, easy to get this wrong)
  c. Otherwise, just blindly assume that 304 responses are using text/html content types (not recommended, not necessarily true)
2. Update service to disable caching. Note that just clearing the cache at the start of the scan is probably **not** sufficient; it's feasible for an auth scenario to involve a single scan doing a redirect chain from a page under test to an auth server back to the same page under test and involve caching behavior within the scope of a single scan.
3. Update service to use Playwright instead of Puppeteer; Playwright's behavior here is to give back a response which uses the status/headers from the original cached 200 response instead of the 304 response, which sidesteps the issue

## Area

- [ ] Install script
- [ ] Update script
- [x] Scan CLI
- [?] Service - I'm not sure whether this also impacts the service outside the scan CLI

## To Reproduce

The following repro script runs a repro server with the necessary response pattern and also demonstrates the relevant Puppeteer behavior in a standalone repro - its only dependency is Puppeteer and recent Node.

```js
const { createHash, randomBytes } = require('node:crypto');
const util = require('node:util');
const http = require('node:http');

const port = 3000;
const throwOnRepro = false; // for puppeteer repro script automation
let browserLauncher = require('puppeteer');
let waitUntil = 'networkidle2';

const etagSeed = randomBytes(16);

const server = http.createServer((req, res) => {
    const hash = createHash('sha256');
    hash.update(etagSeed);
    hash.update(req.url, 'utf-8');
    const etag = `"${hash.digest('hex').slice(0, 12)}"`;

    const ifNoneMatch = req.headers['if-none-match'];
    const suffix = ifNoneMatch ? ` (If-None-Match: ${ifNoneMatch})` : '';
    console.log(`[SERVER] [REQUEST ] ${req.url}${suffix}`);
    
    if (req.url === '/redirect') {
        res.setHeader('Location', `http://localhost:${port}/#from-redirect`)
        res.writeHead(302);
        res.end();
        console.log('[SERVER] [RESPONSE] 302 to /#from-redirect')
    } else if (req.url !== '/') {
        res.writeHead(404);
        res.end();
        console.log('[SERVER] [RESPONSE] 404')
    } else if (ifNoneMatch === etag) {
        res.writeHead(304);
        res.end();
        console.log('[SERVER] [RESPONSE] 304')
    } else {
        res.setHeader("Content-Type", "text/html; charset=utf-8");
        res.setHeader('Cache-Control', `max-age=0`);
        res.setHeader('ETag', etag);
        res.writeHead(200);
        res.end(`
            <!DOCTYPE html>
            <h1>Inside index.html</h1>
            <div id="client-root">Content!</div>
            <script>
            window.addEventListener('load', () => {
                if(window.location.hash !== '#from-redirect') {
                    console.log('Initiating redirect via window.location.assign...')
                    window.location.assign('redirect')
                } else {
                    document.getElementById('client-root').innerText = 'Detected as from redirect'
                    history.replaceState("", document.title, window.location.pathname);
                }
            });
            </script>
        `);
        console.log(`[SERVER] [RESPONSE] 200 (ETag: ${etag})`);
    }
});

async function logResponse(response) {
    const request = response.request();
    responseDebugInfo = {
        url: response.url(),
        status: response.status(),
        statusText: response.statusText(),
        headers: response.headers(),
        redirectChainUrls: request.redirectChain?.()?.map(req => req.url()) ?? undefined,
        fromCache: response.fromCache?.(),
        text: await response.text()
    };

    console.log(util.inspect(responseDebugInfo));
}

server.listen(port, 'localhost', async () => {
    console.log(`Server listening on port ${port}, starting test`);

    const browser = await browserLauncher.launch({ headless: false });
    const page = await browser.newPage();

    console.log(`first await page.goto('http://localhost:${port}/')`)
    const response = await page.goto(`http://localhost:${port}/`, { waitUntil });
    await logResponse(response);
    
    await browser.close();

    if (throwOnRepro) {
        if(!response.fromCache()) {
            throw new Error(`Response text() came from cache (status ${response.status()}), but fromCache() is ${response.fromCache()}`);
        } else if(response.headers['Content-Type'] !== 'text/html; charset=utf-8') {
            throw new Error(`Response has unexpected Content-Type: ${response.headers['Content-Type']}`);
        }
    } else {
        console.log(`Leaving test server running at http://localhost:${port} for manual testing, Ctrl+C to exit`);
    }
});
```

Repro steps:

1. Save the above script as `repro.js`
4. `npm install puppeteer`
5. ` node ./repro.js` (leaves a test server running at `http://localhost:3000`)
6. (different terminal) Build the scan CLI package
7. `node C:\repos\accessibility-insights-service\packages\cli\dist\ai-scan-cli.js --crawl --url http://localhost:3000 --restart --maxUrls 1`

## Expected behavior

Above repro site should scan successfully

## Actual behavior

Above repro steps result in error with log file starting with:

```
[
  {
    "url": "http://localhost:3000",
    "error": "{\n  errorType: 'HttpErrorCode',\n  statusCode: 304,\n  statusText: 'Not Modified',\n  message: 'Page returned an unsuccessful response code',\n <snip>
```

## Log files

see above

## Screenshots

n/a

## Additional context

The error comes from this specific `response.ok()` check in `packages\scanner-global-library\src\page-response-processor.ts`:

https://github.com/microsoft/accessibility-insights-service/blob/8e7e70dd94b6ec13c08b6359ef900685cb324f09/packages/scanner-global-library/src/page-response-processor.ts#L14

However, note while fixing this that this is *not* the only place checking for `ok()`; the rest of the codebase should be audited for usages of `ok()` to ensure everything remains self-consistent.

**Comment by lamaks** [comment]
Resolved in version 2.1.0 https://www.npmjs.com/package/accessibility-insights-scan
