### ISSUE TITLE
[Bug] Can't run as root due to absence of chrome flags

### ISSUE THREAD

**Issue by az-catch** [microsoft/accessibility-insights-service#2437]
## Describe the bug

run cli as root and you get a chrome error:

`Running as root without --no-sandbox is not supported. See https://crbug.com/638180`

## Area

- NPM CLi

## To Reproduce

1. run `ai-scan` as root
2. fails with `Running as root without --no-sandbox is not supported. See https://crbug.com/638180`

## Expected behavior

it works.

**Comment by lamaks** [comment]
Resolved in accessibility-insights-scan@2.1.1
