### ISSUE TITLE
[Bug] Crawling regression between version 1.7.0 and version 2.1.1

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-service#2450]
## Describe the bug

https://github.com/microsoft/accessibility-insights-action/pull/1718 moves from ai-scan 1.7.0 to 2.1.1. There were some formatting changes that we had to adjust, but we found a regression in the crawler. A simplified view of our web site is as follows (this omits the content of the `linked1` and `linked2` folders):

```
/
  /linked1
    ... omitted for brevity
  /linked2
    ... omitted for brevity
  /unlinked
    index.html
    other.html
```

When we set `inputUrls` to `./unlinked/`, the scanner works as expected. When we set `inputUrls` to `./unlinked/index.html`, the scanner times out. The same test works as expected when using ai-scan version 1.7.0.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

## To Reproduce

1. Clone https://github.com/microsoft/accessibility-insights-action/tree/DaveTryon/investigate-scan-timeout (this is a branched from https://github.com/microsoft/accessibility-insights-action/pull/1718 with other e2e tests stripped out)
2. yarn install
3. yarn build
4. yarn test:e2e to see the failure

## Expected behavior

Since scanning `./unlinked/` succeeds, we expect scanning of `./unlinked/index.html` to also succeed.

## Log files

Here is a snipped of the offending log file
```
Scanning URL http://localhost:39983/
Starting accessibility scanning of URL http://localhost:39983/
Chrome app executable: default (bundled with task)
 PuppeteerCrawler: Starting the crawl
 Navigate page to URL. {"requestId":"Ir7SvNTWkzJQd4Q","url":"http://localhost:39983/unlinked/index.html"}
 Processing loaded page. {"url":"http://localhost:39983/unlinked/index.html"}
 Enqueued 1 new links. {"url":"http://localhost:39983/unlinked/index.html"}
 Navigate page to URL. {"requestId":"popY6iV78AF6eEp","url":"http://localhost:39983/"}
 Processing loaded page. {"url":"http://localhost:39983/"}
 Enqueued 2 new links. {"url":"http://localhost:39983/"}
 Navigate page to URL. {"requestId":"dRHjQ6cFbMJaL0R","url":"http://localhost:39983/unlinked/other.html"}
 Processing loaded page. {"url":"http://localhost:39983/unlinked/other.html"}
 Enqueued 1 new links. {"url":"http://localhost:39983/unlinked/other.html"}
 Navigate page to URL. {"requestId":"AJPJtWeTrYIC3Yj","url":"http://localhost:39983/linked1/"}
 Processing loaded page. {"url":"http://localhost:39983/linked1/"}
 Enqueued 2 new links. {"url":"http://localhost:39983/linked1/"}
 Navigate page to URL. {"requestId":"L0ltIGnYj228UtL","url":"http://localhost:39983/linked2/"}
 Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":13764,"requestsFinishedPerMinute":4,"requestsFailedPerMinute":0,"requestTotalDurationMillis":55054,"requestsTotal":4,"crawlerRuntimeMillis":60023,"retryHistogram":[4]}
 PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
 Processing loaded page. {"url":"http://localhost:39983/linked2/"}
 Enqueued 1 new links. {"url":"http://localhost:39983/linked2/"}
 Navigate page to URL. {"requestId":"YyyhPUuyWkCR16t","url":"http://localhost:39983/unlinked/"}
Scan timed out after 90 seconds
```

**Comment by lamaks** [comment]
Not true regression but new e2e test case. Timeout comes from action e2e test not crawler library.

The new test proposed modifies input `inputUrls` parameter to new URL `http://localhost:39983/unlinked/index.html`. This URL is not a web folder but a web page. Hense crawler scans only `http://localhost:39983/unlinked/index.html` web page. No future discovery is possible using `inputUrls` parameter as a discovery pattern.

The crawler library has `discoveryPatterns` parameter to explicitly define URL as a base for links discovery. Adding `discoveryPatterns` parameter to [e2e test](https://github.com/microsoft/accessibility-insights-action/blob/c28a9f7ac132f8939aefe7eaeee8d114d4b92014/packages/ado-extension/e2e/ado-extension.test.ts#L98) allow test to pass.

```
        inputs = {
            staticSiteDir: path.join(__dirname, '..', '..', '..', 'dev', 'website-root'),
            staticSitePort: '39983',
            inputUrls: 'http://localhost:39983/unlinked/index.html',
            discoveryPatterns: 'http://localhost:39983/unlinked/',
        };
```

**Comment by DaveTryon** [comment]
@lamaks and I discussed this online. It looks like the e2e test was somewhat malformed. Closing
