### ISSUE TITLE
JDK available for Microsoft Accessibiilty Insights

### ISSUE THREAD

**Issue by anadin1001** [microsoft/accessibility-insights-service#2585]
Hello, 
I am currently working on a Java-based project that performs web page scans and generates accessibility reports. I would like to enhance the accessibility insights in our application by integrating Microsoft Accessibility Insights. However, I have encountered a limitation, as it appears there is no JDK available for Accessibility Insights.

Could you please advise if there is an existing JDK, or any recommended solution, that would allow us to integrate Accessibility Insights directly within a Java environment? Any guidance on potential alternatives or workarounds to achieve this integration would be greatly appreciated.

Thank you very much for your time and assistance.

**Comment by lamaks** [comment]
@anadin1001 You may want to look into [axe-core-maven-html](https://github.com/dequelabs/axe-core-maven-html) package instead.
