### ISSUE TITLE
[Bug] GET scan result HTTP payload malformed when scan failed

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#319]
The GET scan response HTTP payload malformed and contains misleading data (see below). The payload should be in the following format:

{
    "scanId": "1e9dc9b0-2522-6411-f0d5-cc6817d96315",
    "url": "https://support.microsoft.com/en-us",
    "run": {
        "state": "failed",
        "timestamp": "2019-09-21T18:13:54.812Z",
        "error": ""
    }
}

**Malformed** payload:
{
    "scanId": "1e9dc9b0-2522-6411-f0d5-cc6817d96315",
    "url": "https://support.microsoft.com/en-us",
    "scanResult": {
        "state": "unknown",
        "issueCount": 0
    },
    "reports": [
        {
            "reportId": "",
            "href": "",
            "format": "sarif"
        }
    ],
    "run": {
        "state": "failed",
        "timestamp": "2019-09-21T18:13:54.812Z",
        "error": "{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded..."
    }
}

**Comment by ferBonnin** [comment]
since this is closed marking it as resolved
