### ISSUE TITLE
[Bug] Batch pool intermittent Internet connectivity may require scan run retry

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#321]
The batch pool may experience intermittent Internet connectivity issue. This may require re-run failed scans.

{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded\n    at Promise.then (/mnt/batch/tasks/shared/batch-web-api-scan-runner/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)\n  -- ASYNC --\n    at Frame.<anonymous> (/mnt/batch/tasks/shared/batch-web-api-scan-runner/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/mnt/batch/tasks/shared/batch-web-api-scan-runner/node_modules/puppeteer/lib/Page.js:629:49)\n    at Page.<anonymous> (/mnt/batch/tasks/shared/batch-web-api-scan-runner/node_modules/puppeteer/lib/helper.js:112:23)\n    at Page.<anonymous> (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180776:55)\n    at Generator.next (<anonymous>)\n    at /mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180753:71\n    at new Promise (<anonymous>)\n    at module.exports.../scanner/dist/page.js.__awaiter (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180749:12)\n    at Page.scanForA11yIssues (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180775:16)\n    at Scanner.<anonymous> (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180897:40)\n  -- ASYNC --\n    at Page.<anonymous> (/mnt/batch/tasks/shared/batch-web-api-scan-runner/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.<anonymous> (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180776:55)\n    at Generator.next (<anonymous>)\n    at /mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180753:71\n    at new Promise (<anonymous>)\n    at module.exports.../scanner/dist/page.js.__awaiter (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180749:12)\n    at Page.scanForA11yIssues (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180775:16)\n    at Scanner.<anonymous> (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180897:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/mnt/batch/tasks/workitems/on-demand-url-scan-schedule/job-1534/task_acb3de9c-3155-4779-9944-f8a7b3e9e7e5_81d9e3eee4a6701c083e/wd/web-api-scan-runner.js:180873:58) name: 'TimeoutError' }

**Comment by manishsat** [comment]
Punt for now, we are not going to retry and customer will resend the request.
