### ISSUE TITLE
[Bug] Improve ICM alert actionable diagnostic information

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#331]
**Describe the bug**

**Area**
- [ ] Install script
- [ ] Update script
- [ ] Service

**To Reproduce**

**Expected behavior**

**Log files**
If applicable, any log files / console output that might help explain what the issue might be.

**Screenshots**

**Additional context**

**Comment by markreay** [comment]
This was largely addressed by the telemetry service. We will revisit if experience shows we need more.
