### ISSUE TITLE
[Bug] Add cost insights dashboard widget for prod subscription

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#333]
**Describe the bug**

**Area**
- [ ] Install script
- [ ] Update script
- [ ] Service

**To Reproduce**

**Expected behavior**

**Log files**
If applicable, any log files / console output that might help explain what the issue might be.

**Screenshots**

**Additional context**

**Comment by flyingUnderTheRadar** [comment]
Please sync with @manishsat before going ahead on this one.

**Comment by ferBonnin** [comment]
@manishsat I think this is done, am I correct?

**Comment by manishsat** [comment]
@ferBonnin we can close this since we have Azure spend dashboard in s360
