### ISSUE TITLE
[Bug] Establish staging validation process & add release notes support

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#335]
**Describe the bug**

**Area**
- [ ] Install script
- [ ] Update script
- [ ] Service

**To Reproduce**

**Expected behavior**

**Log files**
If applicable, any log files / console output that might help explain what the issue might be.

**Screenshots**

**Additional context**

**Comment by manishsat** [comment]
Validation documentation is in place. We will pick up how to add release notes later.

**Comment by markreay** [comment]
Staging validation in place. Release notes have not been requested and will be provided in the future if there is sufficient call for it.
