### ISSUE TITLE
[Bug] Retry for assigning managed identity to VMSS resource groups

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-service#340]
Currently, the installation script does not check the existence of VMSS resource groups or retry when enabling system-assigned managed identity. This can cause errors if the resource group does not yet exist.

**Comment by devaradhanm** [comment]
From support team:
perform a check if  VMSS has successfully deployed before running the cli command

when doing az vmss list --query "$vmssNameQuery" -o ts, also check the status of the vmss before accessing nodes.
