### ISSUE TITLE
[Bug] Requests storage queue size should correlate with batch pool size

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#346]
To support scan priority processing the request storage queue size should be small enough to not hold priority scan request for too long. Optimal queue size should be 2x of a single batch processing ie priority message should be red no longer than 2x time of average single message  processing.
To achieve this batch pool manager calculated size data need to be connected with scan request sender.

**Comment by markreay** [comment]
Will be addressed in performance feature. Will close once details have been transferred there.

**Comment by lamaks** [comment]
Will be resolved by future pipeline architecture work to support multiple priorities queues
