### ISSUE TITLE
[Bug] REST API scan result report link host should be APIM host

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#349]
The REST API is exposed through Azure API Management service. The scan response report link should have APIM host name instead of Azure Function host name.

The Azure APIM should have policy added that set Forwarded HTTP header. The func app should use Forwarded host=<host> header to set correct host name in a report link. Reference to [Add a Forwarded header](https://docs.microsoft.com/en-us/azure/api-management/policies/set-header-to-enable-backend-to-construct-urls) policy example.

  {
    "scanId": "1e9e4937-6a37-64e1-cfd4-85cdcfb8ec2e",
    "url": "https://code.visualstudio.com/",
    "scanResult": {
      "state": "fail",
      "issueCount": 6
    },
    "reports": [
      {
        "reportId": "1e9e493a-bd7c-61c0-bfcd-316aa1961397",
        "format": "sarif",
        "links": {
          "rel": "self",
          "href": "https://**web-api-allyfuncappgghrfwzvmcdly.azurewebsites.net**/api/scans/1e9e4937-6a37-64e1-cfd4-85cdcfb8ec2e/reports/1e9e493a-bd7c-61c0-bfcd-316aa1961397?api-version=1.0"
        }
      }
    ],
    "run": {
      "state": "completed",
      "timestamp": "2019-10-01T21:37:30.587Z"
    }
  },

**Comment by ferBonnin** [comment]
since this is closed marking it as resolved
