### ISSUE TITLE
[Bug] Throttle client requests on API management, in case of high traffic.

### ISSUE THREAD

**Issue by manishsat** [microsoft/accessibility-insights-service#385]
## Describe the bug

Throttle client requests on API management, in case of high traffic.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by AhmedAbdoOrtiga** [comment]
Here's the information I shared in the Team chat before, I think it'll be helpful:

We can use API Management access restriction policies to do that, there's four policies I think we might need to consider using (2 of them are unavailable in consumption tier of API Management):

 

1- Limit call rate by subscription: The rate-limit policy prevents API usage spikes on a per subscription basis by limiting the call rate to a specified number per a specified time period. When this policy is triggered the caller receives a 429 Too Many Requests response status code.

 

2- Limit call rate by key(unavailable in consumption tier of API Management): The rate-limit-by-key policy prevents API usage spikes on a per key basis by limiting the call rate to a specified number per a specified time period. The key can have an arbitrary string value and is typically provided using a policy expression. Optional increment condition can be added to specify which requests should be counted towards the limit. When this policy is triggered the caller receives a 429 Too Many Requests response status code.

 

3- Set usage quota by subscription: The quota policy enforces a renewable or lifetime call volume and/or bandwidth quota, on a per subscription basis.

 

4- Set usage quota by key(unavailable in consumption tier of API Management): The quota-by-key policy enforces a renewable or lifetime call volume and/or bandwidth quota, on a per key basis. The key can have an arbitrary string value and is typically provided using a policy expression. Optional increment condition can be added to specify which requests should be counted towards the quota. If multiple policies would increment the same key value, it is incremented only once per request. When the call limit is reached, the caller receives a 403 Forbidden response status code.

 

For more info:

https://docs.microsoft.com/en-us/azure/api-management/api-management-sample-flexible-throttling

https://docs.microsoft.com/en-us/azure/api-management/transform-api

https://docs.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies

![MicrosoftTeams-image](https://user-images.githubusercontent.com/45858632/68149006-f5726880-fef1-11e9-99d9-ceed4e135113.png)

**Comment by markreay** [comment]
Will be addressed in performance feature. Will close once details have been transferred there.

**Comment by ferBonnin** [comment]
@lamaks @manishsat per the comment below, do we still need this bug?
