### ISSUE TITLE
[Feature] Remove batching from our API's

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [microsoft/accessibility-insights-service#405]
## Is your feature request related to a problem? Please describe.

Spoke with @manishsat and he mentioned batching is no longer required and we should remove batching from our API spec and implementations.

## Describe the solution you'd like

This work will include changing the API spec as well as cutting down unwanted code in the API layer only. Both submit and get will no longer be batched.
- Post scans will take in a single URL with priority
- There will be a single GET scan endpoint that takes in a single url. The batch endpoint will be dropped as part of a different feature.
- The GET report endpoint remains unchanged.

Scope is limited to changing the API spec and API layer. Everything else will remain as is and everything underneath is still handled the same way. A separate feature will work to remove the flab and re-architect everything below the API layer.

Work with Uday and come up with a way to transition smoothly.

**Comment by ferBonnin** [comment]
Per conversation with Manish, moving this to bug.
