### ISSUE TITLE
[Bug] Functions debugging documentation is no longer accurate.

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [microsoft/accessibility-insights-service#408]
## Describe the bug
In general the documentation is very sparse. The documentation that is present is wrong (asks for the function host to be started" before starting the debug from VS Code. This isn't true. As a part of debugging it does start up the host. 

## Area

- [ ] Install script
- [ ] Update script
- [X] Service

**Comment by lamaks** [comment]
The documentation portion about how to debug Azure function is correct and up-to-date. No ask to start host, ask is start VS debugger only.

**Comment by manishsat** [comment]
Closing it since we have the documentation already in place, feel free to re-open it if needed.
