### ISSUE TITLE
[Bug] Limited schema validation can lead to wrong errors.

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [microsoft/accessibility-insights-service#409]
## Describe the bug
```
{
    "url": "https://www.bing.com",
    "priority": 0
}
```
 instead of 
```
[
  {
    "url": "https://www.bing.com",
    "priority": 0
  }
]
```
will error on `invalid url` / 500 instead of malformed request and consequently be harder to debug for a consumer.

## Area

- [ ] Install script
- [ ] Update script
- [x] Service

**Comment by manishsat** [comment]
Will be take care of as a part of the feature, closing here.
