### ISSUE TITLE
[Bug] E2E tests results are missing when health monitoring orchestration reports unavailability

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#489]
When health monitoring orchestration reports unavailability E2E tests must provide results to easy diagnosis the service failure point. This bug renders out all benefit of running e2e in production.

<img width="1513" alt="Screen Shot 2020-01-24 at 12 08 10 PM" src="https://user-images.githubusercontent.com/40576301/73100439-68acca80-3ea2-11ea-8a4d-34599c5f2fcc.png">

**Comment by haonliu** [comment]
Did this happen because of web api function app is down? @lamaks
