### ISSUE TITLE
[Bug] Restrict access to Azure Worker function instance to Cosmos DB IP range only

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#496]
Restrict access to Azure Worker function instance to Cosmos DB service 's IP range only

https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions

**Comment by ferBonnin** [comment]
@lamaks is this one done by any chance?

**Comment by lamaks** [comment]
Will require full vnet setup for the entire service. Currently is out of scope.
