### ISSUE TITLE
[Bug] Investigate using SAS tokens instead of access keys for accessing Azure Blob storage

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#498]
Investigate using SAS tokens instead of access keys for accessing Azure Blob storage

Corresponding Azure DevOps task: [User Story 1672989](https://mseng.visualstudio.com/1ES/_workitems/edit/1672989): Investigate using SAS tokens instead of access keys for accessing Azure Blob Storage

**Comment by ferBonnin** [comment]
@lamaks do we still need this bug?

**Comment by lamaks** [comment]
The Blob storage operation is done by a middle-tier service and there is no connection Blob with a client. Middle-tier service use secure key vault access to storage key.
