### ISSUE TITLE
[Bug] Building azure functions should be moved to build defintion

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#565]
## Describe the bug
Currently we are building the azure function app(dotnet build ont he csproj) in release definition before publishing. We should be building in the build definition instead & let the release definition do only the deployment.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by lamaks** [comment]
The Azure function app js code is being zipped during deployment when function-app-create.sh runs and invoks **func azure functionapp publish** command. Moving this to build pipeline will not provide any benefits.
