### ISSUE TITLE
[Bug] Add retries for azure function code upload

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#567]
## Describe the bug
After deploying azure function, sometimes the function may not be available to publish code.
In this case running "func azure functionapp publish ..." will silently fail with log:
```
Publishing 'web-api' scripts to 'web-api-allyfuncappxjohj2cwcdj4c' Function App...
Can't find app with name "web-api-allyfuncappxjohj2cwcdj4c"
Successfully published 'web-api' scripts to 'web-api-allyfuncappxjohj2cwcdj4c' Function App.
```

We should check if the azure function exists & retry.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by AhmedAbdoOrtiga** [comment]
fixed in https://github.com/microsoft/accessibility-insights-service/pull/590
