### ISSUE TITLE
[Bug] Add resource group tag on the vmss created by batch to track

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#570]
## Describe the bug
Since the batch account name is not user friendly like resource group, it is hard to find all vmss that were created for a batch account under a resource group. it would make it easier to find all vmss by the resource group name instead.

We need to add a tag on vmss created by batch account using command like below:
`az resource update --set tags.ResourceGroup='<batchResourceGroupName>' -g <vmss resource group name> -n <vmss name> --resource-type Microsoft.Compute/virtualMachineScaleSets`
 Refer https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#azure-cli

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by AhmedAbdoOrtiga** [comment]
Fixed in PR https://github.com/microsoft/accessibility-insights-service/pull/572
