### ISSUE TITLE
[Bug] Use a common api management to route all Function Apps

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#627]
## Describe the bug
Api management & cosmos are the two expensive components for each dev environment setup.

api management alone contributes to 14.22$ per day. Hosting multiple web apis to the same api management & using the same subscription/product will help us reduce this cost.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by pownkel** [comment]
Instead of using a single APIM instance, we changed from Standard to Developer tier in the dev environment (Standard costs .95/hr and Developer is 0.07/hr). Closing this issue.
