### ISSUE TITLE
[Bug] Avoid using standard_d11_v2 for dev environment

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#628]
## Describe the bug
Currently we have four batch pools.
2 vmss(standard_d1_v2) with 2 nodes & 1 core count - 1.65$ per day each
2 vmss(standard_d11_v2) with 3 nodes & 2 core count - 6.45$ per day each.

We don't need the higher configuration for dev environment. At least not for the legacy pool.
For the new workflow pool we can use standard_d1_v2 with 2 nodes or standard_d11_v2 with 1 node. We can start with former & then move to standard_d1_v2 if we see perf issues.

Using standard_d1_v2  with 2 nodes will bring down cost from 12.9$ to 3.3$ for these two pools per day.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by pownkel** [comment]
Instead of using a single APIM instance, we changed from Standard to Developer tier in the dev environment (Standard costs .95/hr and Developer is 0.07/hr). Closing this issue.

**Comment by pownkel** [comment]
Closed this by accident. Reopening.
