### ISSUE TITLE
[Bug] request package is deprecated

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#744]
## Describe the bug
[Request ](https://www.npmjs.com/package/request) package is deprecated. We can consider using [node-fetch](https://www.npmjs.com/package/node-fetch) package or other similar packages instead.

**Comment by ferBonnin** [comment]
@manishsat do you know what is the state for this bug? thanks!

**Comment by manishsat** [comment]
@ferBonnin we need to plan for this upgrade.
