### ISSUE TITLE
Accessibility Insights (WCP) - Exception Handling

### ISSUE THREAD

**Issue by chjaya-a11y** [microsoft/accessibility-insights-service#750]
## **Is your feature request related to a problem? Please describe.**
AI that is integrated in WCP do not have a way to handle bug exceptions. Some bugs may be exempted Eg: Duplicate Id errors. The scan do not have a way to exempt those bugs instead, continue to show as error every month when a scan is run. This causes churns to the product owns to review the error report each time and cautiously ignore and not act on it.

**## Describe the solution you'd like**
Ability for the AI to capture exceptions and not show them as errors.

**Comment by animania4ka** [comment]
We talked to the requester, closing from our board, as this request is not on our side.
