### ISSUE TITLE
Accessibility Insights (WCP): Capture media assets when scanning dynamic contents

### ISSUE THREAD

**Issue by chjaya-a11y** [microsoft/accessibility-insights-service#751]
**## Is your feature request related to a problem? Please describe.**
Some websites have dynamic content and it makes it hard for the teams to investigate the error if they don't have the exact snapshot or any sort of media asset to understand what content has failed when the scan was run.

## **Describe the solution you'd like**
Add the ability to do a media asset (recorded video or a screen capture) of the dynamic content to see what the experience that was scanned while an error was generated.

**Comment by animania4ka** [comment]
Transitioning to internal feature board.
