### ISSUE TITLE
Autorun AI checks on Page load

### ISSUE THREAD

**Issue by chjaya-a11y** [microsoft/accessibility-insights-service#752]
## Is your feature request related to a problem? Please describe.

This feature brought up by few site owners that they would like to see Accessibility insights running automatically when a page loads from the browser instead of having to install the add-on as it often gets forgotten. It is indeed a great tool but will be nice to have this integrated within browser and show the error numbers.

## Describe the solution you'd like

Integrated in Edge and other browsers as you see fit.

**Comment by animania4ka** [comment]
As such the request is not feasible, we can talk about middle ground. Closing this issue from the GH board and we can transition it.
