### ISSUE TITLE
[Bug] Add unused node count to Node state graph in dashboard & setup ICM alerts

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-service#772]
## Describe the bug

![image](https://user-images.githubusercontent.com/29855291/80997352-0430ce00-8df6-11ea-8c1f-72d256eb39d0.png)

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by lamaks** [comment]
Dashboard has been updated and IcM alert was created

<img width="815" alt="Screen Shot 2020-05-28 at 12 10 25 PM" src="https://user-images.githubusercontent.com/40576301/83183202-4b03a200-a0dc-11ea-9132-2da8dc5c215f.png">
