### ISSUE TITLE
[Bug] Add end-to-end scan request monitoring

### ISSUE THREAD

**Issue by manishsat** [microsoft/accessibility-insights-service#840]
## Describe the bug

Once scan request is submitted we need to monitor progress of every step in the process.
please add end-to-end scan request monitoring

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by lamaks** [comment]
The **Scan Request Count by pipeline stages** tile added to services dashboard

![screencapture-portal-azure-2020-05-28-12_02_10](https://user-images.githubusercontent.com/40576301/83182675-8f427280-a0db-11ea-9e98-1d531df62e42.png)
