### ISSUE TITLE
[Bug] Investigate why Job manager task stuck once in a while

### ISSUE THREAD

**Issue by manishsat** [microsoft/accessibility-insights-service#841]
## Describe the bug

Noticed that the job manager task stuck/hung and does not process anything.

Please add alerts in case it happens and add some max clock time out.
When job manager dies due to max clock time out it should wait until all the child tasks are done.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

**Comment by lamaks** [comment]
No hard evidence on why node process is not starting and hangs. The occurrence is very low (approximately once a month) now. The possible mitigation is to create duplicate Batch schedules to eliminate single point of failure. This will let duplicate schedule run while other stuck. The stuck job is auto terminated by Batch after 1 hour.

**Comment by ferBonnin** [comment]
Per Addie, this will need a feature (burst traffic optimization feature). changing tag

**Comment by lamaks** [comment]
@ferBonnin This is work related to Batch scheduling only.

**Comment by lamaks** [comment]
No repro after moving to containers
