### ISSUE TITLE
[Bug] Remove hardcoded packages version from service deployment script

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#866]
The service deployment script includes hardcoded packages version that are not in sync with code. The should be removed and sync meshanism should be implemented instead.

https://github.com/microsoft/accessibility-insights-service/blob/f315635e7e1b0c267ce8e811dee7e570666ad97a/packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh#L57

**Comment by lamaks** [comment]
The bug will be resolved when Docker container support is implemented.

**Comment by ferBonnin** [comment]
> The bug will be resolved when Docker container support is implemented.

remove from board since this will be addressed with feature board

**Comment by lamaks** [comment]
Resolved as part of containerisation work
