### ISSUE TITLE
[Bug] Configure public IP address prefix for Batch scan VMSS

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#870]
Configure public IP address prefix for Batch scan VMSS to enable client IP whitelisting for AI scanner.

https://docs.microsoft.com/en-us/azure/virtual-network/public-ip-address-prefix

**Comment by ferBonnin** [comment]
@lamaks per Addie this is probably already resolved, could you confirm?

**Comment by lamaks** [comment]
@ferBonnin This is request from WCP we still need to implement.

**Comment by ferBonnin** [comment]
Per conversation with Maxim, this has been addressed
