### ISSUE TITLE
[General Question] How does this service handle pages behind login authentication?

### ISSUE THREAD

**Issue by renatoi** [microsoft/accessibility-insights-service#882]
Is it possible to run a11y insights on pages behind authentication? Is there a config to do that? Is it also possible for me to create my own rules/scripts to run with insights?

**Comment by haonliu** [comment]
Hi @renatoi, thanks for reaching out! 

Currently, we do not have support for authentication yet, which means we can only scan publicly available webpage contents. Let me know if you have more questions!

**Comment by renatoi** [comment]
Thanks for the info @haonliu , are there any plans to support that?

**Comment by lamaks** [comment]
We do have plan to support the website auth but probably not in upcoming months.
